export const routes = {
  home: '/',
  carListing: '/cars',
  carDetails: '/cars/:id',
  profile: '/profile',
  admin: '/admin',
  adminDashboard: '/admin/dashboard',
  adminUsers: '/admin/users',
  adminCars: '/admin/cars',
  adminEditCar: '/admin/cars/edit/:id',
  adminTransactions: '/admin/transactions',
  adminAdvertisements: '/admin/advertisements',
  adminAdvertisementsAll: '/admin/advertisements/all',
  adminAdvertisementsSlider: '/admin/advertisements/slider',
  adminAdvertisementsBanners: '/admin/advertisements/banners',
  adminAdvertisementsAnalytics: '/admin/advertisements/analytics',
  adminSettings: '/admin/settings',
  addCar: '/profile/add-car',
  editCar: '/profile/cars/edit/:id',
  wishlist: '/wishlist',
  users: '/admin/users',
  cars: '/profile/cars',
  settings: '/admin/settings',
  profileHome: '/profile',
  profileSettings: '/profile/settings',
  profileBalance: '/profile/balance',
  auth: {
    login: '/login',
    register: '/register',
    forgotPassword: '/forgot-password',
    resetPassword: '/reset-password'
  }
} as const;